### ISSUE TITLE
I'm so confused about the preinstall script

### ISSUE THREAD

**Issue by git-hiroki** [recallwei/unplugin-auto-import-antd#2]
I found the following code in the project's package.json:.
```
...
"preinstall": "npx-only-allow pnpm",
...
```
However, in README.md, it is explicitly stated that it can be installed using other package managers.
My upstream project uses this dependency, but it blocks my installation because of this wrong preinstall script.

This also means that any upstream project that doesn't install via pnpm will report an error about this "only-allow" preinstall scripts, it doesn't make sense and counterintuitive.

Please fix it, I appreciate that.

@recallwei

**Comment by recallwei** [comment]
@git-hiroki Already fixed in `v0.0.2`.
