### ISSUE TITLE
Consider supporting @ant-design/pro-components resolver？

### ISSUE THREAD

**Issue by q1uxu** [recallwei/unplugin-auto-import-antd#3]
Many people who use antd also use @ant-design/pro-components.

**Comment by recallwei** [comment]
I will build a lib named `unplugin-auto-import-antd-pro-components`.
Or just extend this lib with some configs.

**Comment by recallwei** [comment]
For maintainability, this lib already moved to `@bit-ocean/auto-import`, I made an example project, you can see: https://github.com/bit-ocean-studio/infra/tree/main/examples/auto-import/react-vite-antd-pro-components
