### ISSUE TITLE
Use the JEST test to find Referenceer: ATYPOGRAPHY is not defined

### ISSUE THREAD

**Issue by 520Girl** [recallwei/unplugin-auto-import-antd#4]
**unplugin-auto-import-antd configure:**

![image](https://github.com/user-attachments/assets/d94e5510-b39d-45ce-bfbe-90d31bee50af)
**jest use:**

![image](https://github.com/user-attachments/assets/2968d066-2952-4b17-8e2a-5d24019b57e5)
**components use:**

![image](https://github.com/user-attachments/assets/a842b209-bf22-46b8-b6e6-70961d162230)

Unplugin-Auto-IMPORT-ATD automatically imports the antd component. Use the JEST test to find Referenceer: ATYPOGRAPHY is not defined

How to solve it?@ @recallwei

**Comment by recallwei** [comment]
You can take a look at https://github.com/unplugin/unplugin-auto-import/issues/33.
`unplugin-auto-import` is not suitable for use with `jest`. 
You should import components from the package directly.
```js
import { Typography } from 'antd'
```

**Comment by recallwei** [comment]
Auto import Resolver only transforms the component with vite, it's doing nothing for jest.

**Comment by recallwei** [comment]
`unplugin-auto-import-antd` is deprecated. For maintainability, I moved this package to `bit-ocean/infra` monorepo. you can migrate to `@bit-ocean/auto-import` now.
See: https://github.com/bit-ocean-studio/infra/blob/9c6283c929ed678a318e034be6e42e51e2e2519c/packages/auto-import/README.md
