### ISSUE TITLE
还更新吗,最新版本有的组件没有自动导入

### ISSUE THREAD

**Issue by weiyanggod** [recallwei/unplugin-auto-import-antd#5]

**Comment by recallwei** [comment]
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/de43693e-0fd2-4bdb-bb10-5d824a47c30c">
迁移到其他包了，有新组件吗

**Comment by recallwei** [comment]
用 `@bit-ocean/auto-import`

**Comment by weiyanggod** [comment]
> 用`@bit-ocean/auto-import`
我只需要用ant组件库的导入,其他的不用,我看这个里面是放了很多其他的库

**Comment by weiyanggod** [comment]
@bit-ocean/auto-import  里包含了ant吗?我按照文档引入使用ant组件报错了
![image](https://github.com/user-attachments/assets/d2120868-feb9-440d-8072-cf66c5111ec7)

**Comment by recallwei** [comment]
> > 用`@bit-ocean/auto-import`
> > 我只需要用ant组件库的导入,其他的不用,我看这个里面是放了很多其他的库

这是开发依赖（devDependencies），不会打包到你的代码中

**Comment by recallwei** [comment]
> @bit-ocean/auto-import 里包含了ant吗?我按照文档引入使用ant组件报错了 ![image](https://private-user-images.githubusercontent.com/90230348/389335861-d2120868-feb9-440d-8072-cf66c5111ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTg1OTksIm5iZiI6MTczMjQ5ODI5OSwicGF0aCI6Ii85MDIzMDM0OC8zODkzMzU4NjEtZDIxMjA4NjgtZmViOS00NDBkLTgwNzItY2Y2NmM1MTExZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAxMzEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OGZiMDc2NDE4NmM3NzllYmUxZjViNTczOTExODNiMmZhYWZkNWU0MjlkMGUzN2NkZWNhNjU1NzJjZmIzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8cMaRpktEx_O1U4K-kGuYl31MIw02yipe0sIVrh3X6o)

AntdResolvers 改从 `@bit-ocean/auto-import` 里面引入，你 config 里面 resolvers 给注释掉了

**Comment by weiyanggod** [comment]
> > @bit-ocean/auto-import 里包含了ant吗?我按照文档引入使用ant组件报错了 ![image](https://private-user-images.githubusercontent.com/90230348/389335861-d2120868-feb9-440d-8072-cf66c5111ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTg1OTksIm5iZiI6MTczMjQ5ODI5OSwicGF0aCI6Ii85MDIzMDM0OC8zODkzMzU4NjEtZDIxMjA4NjgtZmViOS00NDBkLTgwNzItY2Y2NmM1MTExZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAxMzEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OGZiMDc2NDE4NmM3NzllYmUxZjViNTczOTExODNiMmZhYWZkNWU0MjlkMGUzN2NkZWNhNjU1NzJjZmIzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8cMaRpktEx_O1U4K-kGuYl31MIw02yipe0sIVrh3X6o)
> 
> AntdResolvers 改从 `@bit-ocean/auto-import` 里面引入，你 config 里面 resolvers 给注释掉了

好的

**Comment by weiyanggod** [comment]
哦,Splitter 分隔面板,这个组件是新的

**Comment by weiyanggod** [comment]
> > @bit-ocean/auto-import 里包含了ant吗?我按照文档引入使用ant组件报错了 ![image](https://private-user-images.githubusercontent.com/90230348/389335861-d2120868-feb9-440d-8072-cf66c5111ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTg1OTksIm5iZiI6MTczMjQ5ODI5OSwicGF0aCI6Ii85MDIzMDM0OC8zODkzMzU4NjEtZDIxMjA4NjgtZmViOS00NDBkLTgwNzItY2Y2NmM1MTExZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAxMzEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OGZiMDc2NDE4NmM3NzllYmUxZjViNTczOTExODNiMmZhYWZkNWU0MjlkMGUzN2NkZWNhNjU1NzJjZmIzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8cMaRpktEx_O1U4K-kGuYl31MIw02yipe0sIVrh3X6o)
> 
> AntdResolvers 改从 `@bit-ocean/auto-import` 里面引入，你 config 里面 resolvers 给注释掉了

哦,Splitter 分隔面板,这个组件是新的

**Comment by recallwei** [comment]
@weiyanggod 升级到 `v0.0.49`
